# Generated by Django 5.2.3 on 2025-10-25 02:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='clinical_notes',
            field=models.TextField(blank=True, help_text='Structured clinical notes', null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='encounter_type',
            field=models.CharField(choices=[('CONSULTATION', 'Consultation'), ('FOLLOWUP', 'Follow-up'), ('EMERGENCY', 'Emergency'), ('TELEMEDICINE', 'Telemedicine')], default='CONSULTATION', max_length=50),
        ),
        migrations.AddField(
            model_name='encounter',
            name='is_telemedicine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='encounter',
            name='patient_satisfaction_score',
            field=models.PositiveIntegerField(blank=True, help_text='Patient satisfaction rating (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='risk_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Clinical risk assessment score', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='video_call_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Video call duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='video_quality_rating',
            field=models.PositiveIntegerField(blank=True, help_text='Video quality rating (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='visit_reason',
            field=models.CharField(blank=True, choices=[('ROUTINE', 'Routine Check-up'), ('EMERGENCY', 'Emergency'), ('FOLLOWUP', 'Follow-up'), ('SPECIALIST', 'Specialist Consultation')], max_length=100),
        ),
        migrations.AddField(
            model_name='encounter',
            name='wait_time_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Patient wait time in minutes', null=True),
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_type', models.CharField(choices=[('SOAP', 'SOAP Note'), ('PROGRESS', 'Progress Note'), ('DISCHARGE', 'Discharge Summary'), ('CONSULTATION', 'Consultation Note')], max_length=50)),
                ('template_used', models.CharField(blank=True, help_text='Template used for this note', max_length=100)),
                ('subjective', models.TextField(blank=True, help_text="Patient's description of symptoms")),
                ('objective', models.TextField(blank=True, help_text='Clinical findings and observations')),
                ('assessment', models.TextField(blank=True, help_text='Clinical assessment and diagnosis')),
                ('plan', models.TextField(blank=True, help_text='Treatment plan and recommendations')),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes_set', to='encounters.encounter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
