# Generated by Django 5.2.3 on 2025-10-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_aadhaar_number_patient_alcohol_consumption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='portal_username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
